server:
  port: 7000
  servlet:
    context-path: /ad-sponsor
spring:
  application:
    name: ad-sponsor
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://192.168.31.145:3306/ad?autoReconnect=true
    username: root
    password: root
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
eureka:
  client:
    service-url:
      defaultZone: http://eureka8000.com:8000/eureka/
